read: 
  _target_: your_package.polar.data.read.file_to_df 
  path: data/external/pdm/raw/PredictiveMaintenanceEngineTraining.csv
transform:
  # Transform functions are called in succession
  - _target_: your_package.polar.data.transform.drop_pattern
    pattern: setting.*
split:
  # train test split the data, and separate the labels
  _target_: your_package.model.split.default
  label: label1
  train_size: 0.8
model:
  # Provide a list of models to train and evaluate on the dataset
  model1:
  - _target_: sklearn.preprocessing.StandardScaler
  - _target_: sklearn.linear_model.LogisticRegression
  model2:
  - _target_: sklearn.preprocessing.MinMaxScaler
  - _target_: sklearn.linear_model.LogisticRegression
train:
  _target_: your_package.model.train.sklearn
eval:
  # script for evaluation. Logs performance in mlflow
  _target_: your_package.model.evaluate.binary_class
write:
  # Write the dataset used to a local file
  _target_: your_package.data.write.df_to_file
  path: data/external/pdm/interim/PredictiveMaintenanceEngineTraining.csv
experiment_name: pdm